spring.application.name=hr-oauth
server.port=${PORT:9000}

eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

oauth.client.name=hr-gateway
oauth.client.secret=hr-gateway-secret
